name: publish
on:
  push:
    tags:
    - 'v*.*.*'
jobs:
  pack-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Set version (NBGV)
        uses: dotnet/nbgv@v0.4
        with:
          setAllVars: true

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Pack
        run: dotnet pack -c Release --no-build -o ./artifacts

      - name: Push (NuGet)
        run: dotnet nuget push "./artifacts/*.nupkg" --api-key "${{ secrets.NUGET_API_KEY }}"
